server:
  port: 8080

spring:
    mvc:
        static-path-pattern: "/static/**"
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: "jdbc:mysql://localhost:3306/cotacao"
        username: "root"
        password: "root"
    jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        show-sql: true
