-- MySQL Script generated by MySQL Workbench
-- Fri May 12 10:29:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cotacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cotacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cotacao` DEFAULT CHARACTER SET utf8 ;
USE `cotacao` ;

-- -----------------------------------------------------
-- Table `cotacao`.`moeda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotacao`.`moeda` ;

CREATE TABLE IF NOT EXISTS `cotacao`.`moeda` (
  `id` VARCHAR(40) NOT NULL,
  `nome` VARCHAR(50) NULL,
  `simbolo` VARCHAR(5) NULL,
  `sigla` VARCHAR(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
